version: '3.3'

services:
  auditor:
    build: .
    container_name: auditor
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - deploy/config.env
      - ~/common-config/config.env
